Transferring repo from private to Energinet
distributed-technologies/ceph-helm pull request #1
Opened 2021-02-19 09:30 UTC by jaxels10

I have added the code from my private github repo and also changed the layout of my helm charts to be an operator chart and a cluster chart. This makes more sense for us when it comes to updating Ceph and Rook.

2021-02-23 13:31 UTC, skovbakke commented on docs/install.md
> +Please be aware that if you need to change any settings for the operator, this can be done in the values.yaml file in the rook-ceph directory. Specifically you should set the image-tag. DO NOT SET IT
Please remove all caps.

2021-02-23 13:32 UTC, skovbakke reviewed
Jeg synes det ser fint ud.

2021-03-02 08:24 UTC, MartinSchmidt requested changes
Generally good, I would suggest changing the cluster folder name to chart.

Second, don't use namespaces in the templates, helm overwrites this anyway with the .Release.Namespace variable, so this one should be used instead.

Next Jakob and I have been looking into how to create a CI flow to automatically create a .tgz file for a helm chart, and publish it. I will ask Jakob to write a simple guide, and you can spare with him.

2021-03-02 08:24 UTC, MartinSchmidt commented on README.md
> +
I would suggest a link to the docs/install.md file, so it easy to navigate to the install guide.

2021-03-02 08:24 UTC, MartinSchmidt commented on README.md
> +└───cluster
We have begun writing our best practices for folder structure..
https://github.com/distributed-technologies/wiki/blob/git-structure/git/index.md
So would suggest changing the **cluster** folder to **chart**

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/Chart.yaml
> +appVersion: "1.16.0"
The appVersion is not required, https://helm.sh/docs/topics/charts/
and since it is holding the default value, I suggest removing it to be specific that we have not written anything to it.

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/Chart.yaml
> +description: A Helm chart for Kubernetes
I would prefer a proper description for the chart.
The name should maybe be ceph-cluster or similar since the name might be too generic.

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/templates/block-storageclass.yaml
> +  namespace: rook-ceph
redundant (remove namespace)

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/templates/cluster.yaml
> +  namespace: {{ .Values.namespace }} # namespace:cluster
redundant (remove namespace)

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/templates/dashboard-external-https.yaml
> +  namespace: rook-ceph # namespace:cluster
redundant (remove namespace)

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/templates/dashboard-external-https.yaml
> +    rook_cluster: rook-ceph # namespace:cluster
redundant (remove namespace)

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/templates/filesystem.yaml
> +  namespace: rook-ceph # namespace:cluster
redundant (remove namespace)

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/templates/object.yaml
> +  namespace: rook-ceph # namespace:cluster
redundant (remove namespace)

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/templates/toolbox.yaml
> +  namespace: rook-ceph # namespace:cluster
redundant (remove namespace)

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/values.yaml
> +namespace: rook-ceph
redundant (remove namespace)

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/templates/block-storageclass.yaml
> +    clusterID: rook-ceph # namespace:cluster
use {{ .Release.Namespace }}

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/templates/block-storageclass.yaml
> +  failureDomain: host
Move failure domain to values file

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/templates/block-storageclass.yaml
> +    size: 3
Move replicated size to values file

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/templates/block-storageclass.yaml
> +    csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph # namespace:cluster
use {{ .Release.Namespace }}

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/templates/block-storageclass.yaml
> +    csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph # namespace:cluster
use {{ .Release.Namespace }}

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/templates/block-storageclass.yaml
> +    csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph # namespace:cluster
use {{ .Release.Namespace }}

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/templates/filesystem-storageclass.yaml
> +  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
use {{ .Release.Namespace }}

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/templates/filesystem-storageclass.yaml
> +  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
use {{ .Release.Namespace }}

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/templates/filesystem-storageclass.yaml
> +  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
use {{ .Release.Namespace }}

2021-03-02 08:24 UTC, MartinSchmidt commented on cluster/templates/object.yaml
> +      # Disallow setting pool with replica 1, this could lead to data loss without recovery.
move failure domain and size to values file

2021-03-02 08:24 UTC, MartinSchmidt commented on docs/README.md
> +This is the documentation for the ceph-helm project at Energinet
suggestion, maybe add links to other md files, might be easier for the reader to navigate.

2021-03-02 08:24 UTC, MartinSchmidt commented on docs/install.md
> +Please be aware that if you need to change any settings for the operator, this can be done in the values.yaml file in the rook-ceph directory. Specifically you should set the image-tag. DO NOT SET IT
maybe highligt it with bold ** instead of caps

2021-03-02 08:24 UTC, MartinSchmidt commented on docs/install.md
> +Please be aware that if you need to change any settings for the operator, this can be done in the values.yaml file in the rook-ceph directory. Specifically you should set the image-tag. DO NOT SET IT
Generally, don't write "I" in the documentation, either "We" or "Our recommendation"

2021-03-05 06:55 UTC, jaxels10 commented on docs/install.md
> +Please be aware that if you need to change any settings for the operator, this can be done in the values.yaml file in the rook-ceph directory. Specifically you should set the image-tag. DO NOT SET IT
Changed it to bold

2021-03-08 06:15 UTC, jaxels10 commented on docs/install.md
> +Please be aware that if you need to change any settings for the operator, this can be done in the values.yaml file in the rook-ceph directory. Specifically you should set the image-tag. DO NOT SET IT
Removed caps, put bold instead

2021-03-08 06:22 UTC, jaxels10 commented on README.md
> +
Added link to the install.md file

2021-03-08 06:23 UTC, jaxels10 commented on README.md
> +└───cluster
Changed to cluster

2021-03-08 06:23 UTC, jaxels10 commented on cluster/Chart.yaml
> +appVersion: "1.16.0"
Removed it

2021-03-08 06:25 UTC, jaxels10 commented on cluster/Chart.yaml
> +description: A Helm chart for Kubernetes
Properly described it and changed the name to ceph-cluster

2021-03-08 06:26 UTC, jaxels10 commented on cluster/templates/block-storageclass.yaml
> +  namespace: rook-ceph
Removed

2021-03-08 06:26 UTC, jaxels10 commented on cluster/templates/filesystem-storageclass.yaml
> +  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
Changed to use {{ .Release.Namespace }}

2021-03-08 06:28 UTC, jaxels10 commented on cluster/templates/object.yaml
> +      # Disallow setting pool with replica 1, this could lead to data loss without recovery.
This is being moved in a big PR that moved a lot of values to values.yaml later today, so I will leave this.

2021-03-08 06:31 UTC, jaxels10 commented on docs/README.md
> +This is the documentation for the ceph-helm project at Energinet
Added a link to each of the other .md files

2021-03-08 06:32 UTC, jaxels10 commented on docs/install.md
> +Please be aware that if you need to change any settings for the operator, this can be done in the values.yaml file in the rook-ceph directory. Specifically you should set the image-tag. DO NOT SET IT
Changed to "we"

2021-03-08 06:43 UTC, MartinSchmidt requested changes
Minor changes to fix the helm chart, look in the comments

2021-03-08 06:43 UTC, MartinSchmidt commented on chart/templates/cluster.yaml
> +  namespace: .Release.Namespace # namespace:cluster
First the {{ are missing, but actually, you don't need to specify it here, since helm automatically fills this namespace.

2021-03-08 06:43 UTC, MartinSchmidt commented on chart/templates/filesystem-storageclass.yaml
> +  clusterID: .Release.Namespace
- [ ] Missing {{ }}

2021-03-08 06:43 UTC, MartinSchmidt commented on chart/templates/filesystem.yaml
> +  namespace: .Release.Namespace # namespace:cluster
Remove namespace, it is not required

2021-03-08 06:43 UTC, MartinSchmidt commented on chart/templates/object.yaml
> +  namespace: .Release.Namespace # namespace:cluster
Remove namespace, it is not required

2021-03-08 07:18 UTC, jaxels10 commented on chart/templates/cluster.yaml
> +  namespace: .Release.Namespace # namespace:cluster
Removed

2021-03-08 07:18 UTC, jaxels10 commented on chart/templates/filesystem-storageclass.yaml
> +  clusterID: .Release.Namespace
Added

2021-03-08 07:18 UTC, jaxels10 commented on chart/templates/filesystem.yaml
> +  namespace: .Release.Namespace # namespace:cluster
Removed the namespace

2021-03-08 07:19 UTC, jaxels10 commented on chart/templates/object.yaml
> +  namespace: .Release.Namespace # namespace:cluster
Removed namespace

2021-03-08 08:36 UTC, MartinSchmidt requested changes
Minor change, seems like new files was added, see comment.s

2021-03-08 08:36 UTC, MartinSchmidt commented on chart/templates/dashboard-external-https.yaml
> +    rook_cluster: rook-ceph # namespace:cluster
{{ .Release.Namespace }}

2021-03-08 08:36 UTC, MartinSchmidt commented on chart/templates/dashboard-external-https.yaml
> +  namespace: rook-ceph # namespace:cluster
Is this new? it wasn't here before I think?

- [ ] remove namespace

2021-03-08 08:36 UTC, MartinSchmidt commented on chart/templates/cluster.yaml
> +#################################################################################################################
Is this file new?

2021-03-08 10:04 UTC, jaxels10 commented on chart/templates/dashboard-external-https.yaml
> +    rook_cluster: rook-ceph # namespace:cluster
Deleted the file since it is deleted in the next PR anyway.

2021-03-08 10:04 UTC, jaxels10 commented on chart/templates/dashboard-external-https.yaml
> +  namespace: rook-ceph # namespace:cluster
Deleted the file since it is deleted in the next PR anyway.

2021-03-08 10:05 UTC, jaxels10 commented on chart/templates/cluster.yaml
> +#################################################################################################################
The cluster.yaml file is not new

2021-03-08 11:49 UTC, MartinSchmidt approved these changes

2021-03-08 12:39 UTC, merged